export enum JOB_SEEKER_PROFILE_ACTIONS {
  RESUME_ADD = 'RESUME_ADD',
  RESUME_REMOVE = 'RESUME_REMOVE',
  RESUME_TYPE = 'RESUME_TYPE',

  SKILLS_ADD = 'SKILLS_ADD',
  SKILLS_REMOVE = 'SKILLS_REMOVE',
  SKILLS_TYPE = 'SKILLS_TYPE',

  EXPERIENCE_ADD = 'EXPERIENCE_ADD',
  EXPERIENCE_REMOVE = 'EXPERIENCE_REMOVE',
  EXPERIENCE_TYPE = 'EXPERIENCE_TYPE',
}
